<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLHYXLbd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLHYXLbd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLHYXLbd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLHYXLbd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLHYXLbd\App_KernelDevDebugContainer([
    'container.build_hash' => 'LHYXLbd',
    'container.build_id' => '2a4cefe9',
    'container.build_time' => 1723728546,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLHYXLbd');
